theme: jekyll-theme-primer
title: Using Data to Improve Market Efficiency in Honduras' Power System
description: 
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
